#pragma config(Sensor, S1,     gyro,           sensorEV3_Gyro)
#pragma config(Motor,  motorA,          RightFront,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          RightBack,     tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          LeftFront,     tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorD,          LeftBack,      tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Open a the joystick debugger window
// As soon as the program is run
#pragma DebuggerWindows("joystickSimple")

// Include the joystick driver
#include "JoystickDriver.c"
//Globale variabele
float currHeading;
//De afwijking van de gyro sensor
int offset = 598;	

bool setMotor(float angle, float speed, bool left , bool right);
float getRatio(float angle, char ratio);
float getJoystickAngle(int x, int y);
float getJoystickSpeed(int y);


task main()
{
	setLEDColor(ledRedPulse);

	while (true)
		{
			getJoystickSettings(joystick);			
			setMotor(getJoystickAngle(joystick.joy1_x1, joystick.joy1_y1), getJoystickSpeed(joystick.joy1_y2), joy1Btn(7),joy1Btn(8));
	}
}

bool setMotor(float angle, float speed, bool left , bool right)
{ 
	if ((left) && (!right))
	{
		motor[motorA] = -1 * speed;
		motor[motorB] = speed;
		motor[motorC] = speed;
		motor[motorD] =  -1 * speed;	
	}
	else if ((right) && (!left))
	{
		motor[motorA] = speed;
		motor[motorB] = -1 * speed;
		motor[motorC] = -1 * speed;
		motor[motorD] = speed;
	}
	else
	{	
		motor[motorA] = getRatio(angle, 'A') * speed;
		motor[motorB] = getRatio(angle, 'B') * speed;
		motor[motorC] = getRatio(angle, 'C') * speed;
		motor[motorD] = getRatio(angle, 'D') * speed;
	}
	
	return true;
}

float getJoystickAngle(int x, int y)
{		
	float angle = atan2(x, y);
	float rate = getGyroHeading(gyro);
	if (rate < 0)
	{
		rate = rate + 360;
	}
	angle = (angle/PI) * 180;
	if (angle < 0)
	{
		angle = angle + 360;
	}	
	angle = angle + rate;
	if (angle > 360)
	{
		angle = angle - 360;
	}
	return angle;
}


float getJoystickSpeed(int y)
{
	float	speed = (float) (y /127.0) * 100;	
	if (speed < 0)
	{
		speed = 0;
	}
	return speed;
}

float getRatio(float angle, char ratio)
{
	float ratioAC = 0;
	float ratioBD = 0;
	
	if(angle <= 45)
	{
		ratioAC = 1;
		ratioBD = (45 - angle)/45;
	}
	else if ((angle > 45) && (angle <= 90))
	{
		ratioAC = 1;
		ratioBD = (float) ((angle - 45)/45) * -1;
	}
	else if ((angle > 90) && (angle <= 135))
	{
		ratioAC = (float)(135 - angle)/45;
		ratioBD = -1;
	}
	else if ((angle > 135) && (angle <= 180))
	{
		ratioAC = (float) ((angle - 135) / 45) * -1;
		ratioBD = -1;
	}
	else if ((angle > 180) && (angle <= 225))
	{
		ratioAC = -1;
		ratioBD = (float) ((225 - angle)/45) * -1;
	}
	else if ((angle > 225) && (angle <= 270))
	{
		ratioAC = -1;
		ratioBD = (float) ((angle - 225)/45);
	}
	else if ((angle > 270) && (angle <= 315))
	{
		ratioAC = (float) ((315 - angle)/45) * -1;
		ratioBD = 1;
	}
	else if ((angle > 315) && (angle <= 360))
	{
		ratioAC = (float) (angle - 315)/45;
		ratioBD = 1;
	}	

	if ((ratio == 'A') || (ratio == 'C'))
	{
		return ratioAC;
	}
	else if ((ratio == 'B') || (ratio == 'D'))
	{
		return ratioBD;
	}	
	else
	{
		return 0;
	}
}
