#pragma config(Motor,  motorA,          RightFront,    tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          RightBack,     tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          LeftFront,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorD,          LeftBack,      tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Open a the joystick debugger window
// As soon as the program is run
#pragma DebuggerWindows("joystickSimple")

// Include the joystick driver
#include "JoystickDriver.c"

bool setMotor(int x, int y);
bool setAngle ();
task main()
{
	setLEDColor(ledRedPulse);

	while (true)
		{
			getJoystickSettings(joystick);

		//setMotor(joystick.joy1_x1,joystick.joy1_y1);		
		setAngle();
	}
}

bool setMotor(int x, int y)
{
	
//formules klopen niet meer door dat motors gereverserd zijn!
	if ((( y > 3 ) && ( x < 3) && (x > -3))|| (( y < 3 ) && ( x < 3) && ( x > -3)))
	{
		motor[motorA] = y * -1;
		motor[motorB] =  y;
		motor[motorC] =  y;
		motor[motorD] = y * -1;
	} else if ((( x > 3 ) && ( y < 3) && (y > -3))|| (( x < 3 ) && ( y < 3) && ( y > -3)))
	{
		motor[motorA] =  x;
		motor[motorB] = x;
		motor[motorC] =  x * -1;
		motor[motorD] = x * -1;
	}
	return true;
}

bool setAngle()
{
		motor[motorA] = 20;
		motor[motorB] =  50;
		motor[motorC] =  20;
		motor[motorD] = 50;
	
	return true;
}
